# Generated by Django 3.2.6 on 2021-08-15 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('password_hash', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.BinaryField(max_length=32)),
                ('for_website', models.CharField(max_length=30)),
                ('website_username', models.CharField(max_length=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customerentity')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_website', models.CharField(max_length=30)),
                ('website_username', models.CharField(max_length=30)),
                ('salt_hash', models.BinaryField(max_length=256)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customerentity')),
            ],
        ),
    ]
